### ISSUE TITLE
Linux support in the future?

### ISSUE THREAD

**Issue by antiLimited** [maxnut/GDMegaOverlay#30]
As a Linux user and an geometry dash player it would be nice to have a mod menu compatible with our operating system.

**Comment by rice7th** [comment]
@antiLimited I play GD on linux every day using MHV7, BetterEdit and around 15 different extension. Unfortunately, both GDMegaOverlay and MHV7 get injected into the executable, so unless GD is supported on Linux (and robtop actually said it will be but after 2.2), you can't just port this to Linux. what you can do is making this cross compile, but since again we're talking about ejection, GDMegaOverlay clearly depends on WinAPI. So if you manage to find the winapi headers and if you find a cross compiler like clang or zig cc then yeah you can build this under Linux, but at this point just use a VM.

**Comment by rice7th** [comment]
So, basically, just use proton and it should work fine.

**Comment by MarcelskyXD** [comment]
> So, basically, just use proton and it should work fine.

Doesn't work for me. i put all the DLLs into my gd folder and the mod menu doesnt work

**Comment by Player10000000000** [comment]
how are u playing on Lunix?

**Comment by Xtobyte** [comment]
Put this in the steam launch options and it should work:
WINEDLLOVERRIDES="xinput9_1_0=n,b" %command%
